name: Output Event Details

on:
  issues:
    types:
      - opened
      - edited

jobs:
  output-details:
    runs-on: ubuntu-latest

    steps:
      - name: Output Event Details
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue Author: ${{ github.event.issue.user.login }}"
